branches:
  only:
  - master
matrix:
  include:
  - os: linux
    language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-26.0.0
      - android-25
      licenses:
      - android-sdk-license-.+
    addons:
      apt:
        packages:
        - oracle-java8-installer

before_install:
- rvm install 2.3.1
- gem install bundler
- nvm install v6
- npm update npm
- if [ ${TRAVIS_OS_NAME} = "linux" ]; then jdk_switcher use oraclejdk8; fi
  npm install -g ios-deploy; fi
install:
- npm install -g cordova@6.5.0 ionic@6.5.0 typescript@2.5.3
- npm install
after_success:
- if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ ${TRAVIS_BRANCH} = "master" ] && [ ${TRAVIS_OS_NAME} = "linux" ] && [ ${TRAVIS_TAG} ]; then 
    bundle exec fastlane android deploy target:prod; 
  fi
deploy:
  provider: releases
  api_key:
    secure: MPervNlXGzbxDyith/CiAFd44cwSVGN+ASCrRL2kAzSimo4b9DBKZ09woUzIlk/6/R1R7Z8ZpyjdbGPkyoqarbduujJFL+tL0/2hfjtZ70s7VrmkGpOkxZvHix5X7WYI31gzqBtZpW9Lrnes2wXVuMby7lOTGAaKK00GguwTGhHDdTXOqCwUT9nMGAuARL36mNblTr3JDhKzr1bxBa0okfzVBq7embzq0qMKVKO10WtwWXiaw9UOFGt6pBj18P0w7Kuuq5GaY5Xc17/Mn4oVAJ9Sq6FKgxeITQ0x5X7Ygb6X+IlQkKY8lHe4hW7PTEPyEmHtjADM4ZJf7R6Zk/UCr3+QrXdIUbGxbqKUg6QuVnjKSq0I6QqTEVm3vkUQRLmkO4H/hSCse25FTONjlfZqHmdqu8EsRGaIdNuKLTBtN55Glm2OzT4WUkAuvMiCv7kW+vqvK9vz+P2ZbZH5h+rGgeq0ivr9/nCUTbf/MvddUyw4vNNGuJGMWT9HwW7tH9dT1oYQoQOqLtCEUv5dFi90lZTiLHdsyTfPNOgsOkZkRBHxvNRD+1fupNeCHKPOe1jibSzx6JgEJZgoipAbow5IJFyoJxzEkbr1Wj3zkGszC5v2/SFfinm+h15xvcT9V3I731UqwLmVyIWc+D7UlFzNZJ72wF844kvKMBeeqf4oXOc=
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: MRidwanKurniawan/pwm-akakom
    branch: master
